<<<<<<< HEAD
import { useCallback, useEffect, useState } from 'react'
import { supabase } from '../lib/supabaseClient'
import ProductCard from '../components/ProductCard'
export default function Donaciones() { const [items,setItems]=useState([]); const [loading,setLoading]=useState(true); const [search,setSearch]=useState(''); const [size,setSize]=useState(''); const [condition,setCondition]=useState(''); const [error,setError]=useState('')
 const load=useCallback(async()=>{setLoading(true);let query=supabase.from('publicaciones').select('*').eq('tipo','donacion').eq('estado','activo').order('created_at',{ascending:false});if(search.trim())query=query.or(`titulo.ilike.%${search.trim()}%,descripcion.ilike.%${search.trim()}%`);if(size)query=query.eq('talla',size);if(condition)query=query.eq('condicion',condition);const {data,error:queryError}=await query;if(queryError)setError(queryError.message);else {setError('');setItems(data||[])}setLoading(false)},[search,size,condition]);/* eslint-disable react-hooks/set-state-in-effect */useEffect(()=>{load()},[load]);/* eslint-enable react-hooks/set-state-in-effect */ return <div className="catalog-page"><header className="catalog-hero"><div><span className="eyebrow">Compartir transforma</span><h1>Donaciones</h1></div><p>Prendas listas para empezar una nueva etapa, sin costo para quien las necesite.</p></header><div className="filters"><input value={search} onChange={(event)=>setSearch(event.target.value)} placeholder="Buscar una donación…"/><select value={size} onChange={(event)=>setSize(event.target.value)}><option value="">Todas las tallas</option>{['XS','S','M','L','XL','6','8','10','12','14'].map((item)=><option key={item}>{item}</option>)}</select><select value={condition} onChange={(event)=>setCondition(event.target.value)}><option value="">Todos los estados</option><option>Como nuevo</option><option>Buen estado</option><option>Uso visible</option></select></div>{loading?<div className="page-state">Cargando donaciones…</div>:error?<div className="empty-state">No fue posible cargar las donaciones: {error}</div>:items.length?<div className="product-grid">{items.map((item,index)=><ProductCard product={item} index={index} key={item.id}/>)}</div>:<div className="empty-state">No encontramos donaciones disponibles por ahora.</div>}</div> }
=======
import { useCallback,useEffect,useState } from 'react'; import { supabase } from '../lib/supabaseClient'; import ProductCard from '../components/ProductCard'
export default function Donaciones(){const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[size,setSize]=useState(''),[condition,setCondition]=useState('');const load=useCallback(async()=>{setLoading(true);setError('');let q=supabase.from('publicaciones').select('*').eq('tipo','donacion').eq('estado','activo').order('created_at',{ascending:false});if(search.trim())q=q.or(`titulo.ilike.%${search.trim()}%,descripcion.ilike.%${search.trim()}%`);if(size)q=q.eq('talla',size);if(condition)q=q.eq('condicion',condition);const {data,error:queryError}=await q;if(queryError)setError(queryError.message);else setItems(data||[]);setLoading(false)},[search,size,condition]);/* eslint-disable react-hooks/set-state-in-effect */useEffect(()=>{load()},[load]);/* eslint-enable react-hooks/set-state-in-effect */return <div className="catalog-page"><header className="catalog-hero"><div><span className="eyebrow">Compartir transforma</span><h1>Donaciones</h1></div><p>Prendas listas para empezar una nueva etapa, sin costo para quien las necesite.</p></header><div className="filters"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar una donación…"/><select value={size} onChange={e=>setSize(e.target.value)}><option value="">Todas las tallas</option>{['XS','S','M','L','XL','6','8','10','12','14'].map(x=><option key={x}>{x}</option>)}</select><select value={condition} onChange={e=>setCondition(e.target.value)}><option value="">Todas las condiciones</option><option>Como nuevo</option><option>Buen estado</option><option>Uso visible</option></select></div>{loading?<div className="page-state">Cargando donaciones…</div>:error?<div className="form-error">{error}</div>:items.length?<div className="product-grid">{items.map((x,i)=><ProductCard product={x} index={i} key={x.id}/>)}</div>:<div className="empty-state">No encontramos donaciones disponibles por ahora.</div>}</div>}
>>>>>>> c4dee0c (Completa integracion con Supabase)
