-- Migracion aditiva para DonayViste. No elimina datos existentes.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nombre text not null default '',
  apellido text not null default '',
  email text not null default '',
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.publicaciones (
  id bigint generated by default as identity primary key,
  usuario_id uuid references public.profiles(id) on delete cascade,
  titulo text,
  descripcion text default '',
  precio numeric(12,2) default 0,
  talla text,
  categoria text default 'Uniformes',
  condicion text default 'Buen estado',
  contacto text default '',
  imagen_url text,
  tipo text default 'venta',
  estado text default 'activo',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.publicaciones add column if not exists titulo text;
alter table public.publicaciones add column if not exists descripcion text default '';
alter table public.publicaciones add column if not exists precio numeric(12,2) default 0;
alter table public.publicaciones add column if not exists talla text;
alter table public.publicaciones add column if not exists categoria text default 'Uniformes';
alter table public.publicaciones add column if not exists condicion text default 'Buen estado';
alter table public.publicaciones add column if not exists contacto text default '';
alter table public.publicaciones add column if not exists imagen_url text;
alter table public.publicaciones add column if not exists tipo text default 'venta';
alter table public.publicaciones add column if not exists estado text default 'activo';
alter table public.publicaciones add column if not exists usuario_id uuid;
alter table public.publicaciones add column if not exists created_at timestamptz default now();
alter table public.publicaciones add column if not exists updated_at timestamptz default now();

update public.publicaciones set categoria = 'Uniformes' where categoria is null;
update public.publicaciones set condicion = 'Buen estado' where condicion is null;
update public.publicaciones set descripcion = '' where descripcion is null;
update public.publicaciones set contacto = '' where contacto is null;
update public.publicaciones set precio = 0 where precio is null;
update public.publicaciones set tipo = 'venta' where tipo is null;
update public.publicaciones set estado = 'activo' where estado is null;
update public.publicaciones set created_at = now() where created_at is null;
update public.publicaciones set updated_at = created_at where updated_at is null;

create index if not exists publicaciones_usuario_id_idx on public.publicaciones (usuario_id);
create index if not exists publicaciones_tipo_estado_idx on public.publicaciones (tipo, estado);
create index if not exists publicaciones_categoria_idx on public.publicaciones (categoria);

alter table public.profiles enable row level security;
alter table public.publicaciones enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles for select using (auth.uid() = id);
drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own" on public.profiles for insert with check (auth.uid() = id);
drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "publications_select_public" on public.publicaciones;
create policy "publications_select_public" on public.publicaciones for select using (auth.uid() = usuario_id or estado in ('activo', 'pausado', 'reservado', 'vendido', 'donado'));
drop policy if exists "publications_insert_own" on public.publicaciones;
create policy "publications_insert_own" on public.publicaciones for insert to authenticated with check (auth.uid() = usuario_id);
drop policy if exists "publications_update_own" on public.publicaciones;
create policy "publications_update_own" on public.publicaciones for update to authenticated using (auth.uid() = usuario_id) with check (auth.uid() = usuario_id);
drop policy if exists "publications_delete_own" on public.publicaciones;
create policy "publications_delete_own" on public.publicaciones for delete to authenticated using (auth.uid() = usuario_id);

insert into public.profiles (id, email, nombre, apellido)
select id, email, coalesce(raw_user_meta_data->>'first_name', ''), coalesce(raw_user_meta_data->>'last_name', '')
from auth.users
on conflict (id) do update set email = excluded.email;

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_updated_at on public.profiles;
create trigger profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at();
drop trigger if exists publicaciones_updated_at on public.publicaciones;
create trigger publicaciones_updated_at before update on public.publicaciones for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, nombre, apellido, email)
  values (new.id, coalesce(new.raw_user_meta_data->>'first_name', ''), coalesce(new.raw_user_meta_data->>'last_name', ''), new.email)
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

insert into storage.buckets (id, name, public)
values ('uniformes', 'uniformes', true)
on conflict (id) do update set public = true;

drop policy if exists "uniformes_read_public" on storage.objects;
create policy "uniformes_read_public" on storage.objects for select using (bucket_id = 'uniformes');
drop policy if exists "uniformes_insert_own_folder" on storage.objects;
create policy "uniformes_insert_own_folder" on storage.objects for insert to authenticated
with check (bucket_id = 'uniformes' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "uniformes_update_own_folder" on storage.objects;
create policy "uniformes_update_own_folder" on storage.objects for update to authenticated
using (bucket_id = 'uniformes' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "uniformes_delete_own_folder" on storage.objects;
create policy "uniformes_delete_own_folder" on storage.objects for delete to authenticated
using (bucket_id = 'uniformes' and (storage.foldername(name))[1] = auth.uid()::text);
